### ISSUE TITLE
What's the Project Status?

### ISSUE THREAD

**Issue by FelicianoTech** [velum/lguf-brightness#3]
Hey,

I'm considering getting the Ultrafine 4K and running it with Ubuntu. What is the status of what's working and what isn't with this codebase?

- resolution? (I'm assuming full 4K is already working)
- brightness up/down?
- sleep? Does the monitor wake up from sleep in a timely fashion?
- changing the monitor resolution?

If you have answers for these questions, putting them on the readme would be useful.

Thanks in advance.

**Comment by velum** [comment]
1. 4K is working, but this has nothing to do with the code of this project. I mainly depends on your graphics card;
2. Brightness up/down is working. This is the goal of this project;
3. Yes, the monitor wakes up from sleep, although, I remember people having problems with this, but it might have been with older versions of Linux. One thing though, with my graphics card, the monitor does not really go to sleep. The screen becomes black, but I can still see the cursor, which means the computer is displaying a black screen. It is not the monitor going to sleep;
4. I haven't tried changing the monitor resolution.

**Comment by FelicianoTech** [comment]
Thank you.
